# This is a basic workflow to help you get started with Actions

name: buildrelease

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.9
          # File containing the Python version to use. Example: .python-version
          
      - name: Install Dependencies
        run: |
          pip3 install -U nuitka
          pip3 install -U requests
          pip3 install -U colorama
          pip3 install -U win10toast
          pip3 pip install -U notify2

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  
  build-windows:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.9
          # File containing the Python version to use. Example: .python-version
          
      - name: Install Dependencies
        run: |
          pip3 install -U nuitka
          pip3 install -U requests
          pip3 install -U colorama
          pip3 install -U win10toast
          pip3 install -U notify2

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  build-macos:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.9
          # File containing the Python version to use. Example: .python-version
          
      - name: Install Dependencies
        run: |
          pip3 install -U nuitka
          pip3 install -U requests
          pip3 install -U colorama
          pip3 install -U win10toast
          pip3 install -U notify2

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
